FROM node:20-alpine

# Expose port
EXPOSE 3000/tcp

# Add tini to handle process signals
RUN apk add --no-cache tini

# Create working directory
WORKDIR /usr/src/app

# Copy dependencies definition and install
COPY package*.json ./
RUN npm install --omit=dev && npm cache clean --force

# Copy rest of the app
COPY . .

# Use tini and start the app
CMD ["node", "app.js"]

