FROM python:3.10-slim

WORKDIR /app

EXPOSE 5000/tcp   

LABEL maintainer="tu_nombre@tu_dominio.com"
LABEL version="1.0"
LABEL description="Dockerfile para una aplicacion Python"

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]