apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  expirationSeconds: 3600 #seconds
  usages:
  - digital signature
  - key encipherment
  - server auth
  request: 
