apiVersion: apiextensions.k8s.io/v1
kind:   CustomResourceDefinition
metadata: 
  name: flightticket.flights.com
spec:
  scope: Namespaced
  group: flights.com
  names:  
    kind: FlightTicket
    singular: flightticket
    plural: flighttickets
    shortNames:
    - ft
  versions:
    - name: v1 
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                passengerName:
                  type: string
                flightNumber:
                  type: string
                departure:
                  type: string
                arrival:
                  type: string
                seatClass:
                  type: string 
                from:
                  type: string
                to:
                  type: string
                