apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "delete"]
  resourcesNames: ["blue", "green"]

- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
