apiVersion: v1 
clusters:
- cluster:
    certificate-authority: /path/to/ca.crt
    server: https://kube-apiserver:6443
  name: kubernetes
kind: Config 
users: 
- name: kubernetes-admin
  user:
    client-certificate: /path/to/admin.crt
    client-key: /path/to/admin.key